Updated workflows

diff --git a/.github/workflows/clang_format.yml b/.github/workflows/clang_format.yml
--- a/.github/workflows/clang_format.yml
+++ b/.github/workflows/clang_format.yml
@@ -9,42 +9,19 @@ on:
     - cron: '0 5 * * *'
 
 jobs:
-  industrial_ci:
-    name: Format
-    runs-on: ubuntu-latest
-    env:
-      CI_NAME: Clang-Format
-      OS_NAME: ubuntu
-      OS_CODE_NAME: bionic
-      ROS_DISTRO: melodic
-      ROS_REPO: main
-      CLANG_FORMAT_CHECK: file
-      CLANG_FORMAT_VERSION: 8
+  clang_format:
+    name: Clang Format
+    runs-on: ubuntu-20.04
     steps:
       - uses: actions/checkout@v2
 
-      - name: Free Disk Space
+      - name: Run Clang Format Check
         run: |
-          sudo swapoff -a
-          sudo rm -f /swapfile
-          sudo apt clean
-          docker rmi $(docker image ls -aq)
-          df -h
-
-      - name: Prepare ccache timestamp
-        id: ccache_cache_timestamp
-        shell: cmake -P {0}
-        run: |
-          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
-          message("::set-output name=timestamp::${current_date}")
-
-      - name: ccache cache files
-        uses: actions/cache@v1.1.0
-        with:
-          path: ${{ env.CI_NAME }}/.ccache
-          key: ${{ env.CI_NAME }}-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
-          restore-keys: |
-            ${{ env.CI_NAME }}-ccache-
-
-      - uses: 'ros-industrial/industrial_ci@master'
-        env: ${{env}}
+          sudo apt install clang-format
+          RED='\033[0;31m'
+          NC='\033[0m' # No Color
+          ./.run-clang-format
+          output=$(git diff)
+          if [ -n "$output" ]; then printf "${RED}Clang format error: run script './.run-clang-format'${NC}\n"; fi
+          if [ -n "$output" ]; then printf "${RED}${output}${NC}\n"; fi
+          if [ -n "$output" ]; then exit 1; else exit 0; fi
